### ISSUE TITLE
is "ServerReflection service" part of php-grpc ? 

### ISSUE THREAD

**Issue by nicocesar** [spiral/php-grpc#25]
I'm testing out with grpc_cli and I get a successful call: 

```
$ grpc_cli call --protofiles service.proto  127.0.0.1:9002 Echo.Ping 'msg: "Nico"'
connecting to 127.0.0.1:9002
msg: "NICO"

Rpc succeeded with OK status
Reflection request not implemented; is the ServerReflection service enabled?

```
but the last message suggests that I have to do something similar to 
https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md

In the go libraries this support is part of the tool, but php-grpc doesn't seem to have a similar way to do this.

Is there a non-documented feature that could enable this easily?

**Comment by wolfy-j** [comment]
PHP-GRPC currently does not support this feature. There is a limitation of how the proxy is operating. We will def going to take a look at it in the future. Any help appreciated.

**Comment by nicocesar** [comment]
Can you expand on the limitation ? I'll be happy to give a hand on this if needed... but I want to understand the problem a little bit better.

**Comment by wolfy-j** [comment]
Currently, php-grpc does not compile profobuf definition in order to operate. I just parse the original proto file to get the list of methods and services. It might not be enough for reflection API. To change it, we have to load compiled proto file into proxy (in binary form). It's not hard but it will require some changes in the integration flow.

Reference:
https://github.com/spiral/php-grpc/blob/master/service.go#L171
